# Generated by Django 3.2.6 on 2021-12-17 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.register')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('SBI', 'SBI'), ('FEDERAL', 'FEDERAL'), ('UNION', 'UNION'), ('CANARA', 'CANARA')], default='SBI', max_length=30)),
                ('branch', models.CharField(max_length=50)),
                ('acc_no', models.IntegerField()),
                ('ifsc', models.IntegerField()),
                ('pan', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('sdate', models.DateField(default=django.utils.timezone.now)),
                ('edate', models.DateField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.register')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
