# Generated by Django 3.2.6 on 2021-12-18 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20211218_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
